# cth Cara Kerja Stack atau Tumpukan
print(5*'===========')
print('                    STACKS')
print(5*'===========')
data = [1,2,3,4,5]
print('Data Sekarang :',data)
print(5*'===========')
data.append(6)                          # append metode untuk menambah isi list
print('Data Masuk :',6)
print('Data Sekarang :',data)
print(5*'===========')
data.append(7)
print('Data Masuk :',7)
print('Data Sekarang :',data)
print(5*'===========')
out = data.pop()
print('Data Keluar :',out)
print('Data Sekarang :',data)
print(5*'===========')
out = data.pop()
print('Data Keluar :',out)
print('Data Sekarang :',data)
print(5*'===========','\n')

# cth Cara Kerja queue atau antrian
print(5*'===========')
print('                    QUEUE')
print(5*'===========')
from collections import deque
datadeque = deque([0,1,2,3,4,5])
print('Data Sekarang :',datadeque)
print(5*'===========')
datadeque.append(6)
print('Data Masuk :',6)
print('Data Sekarang :',datadeque)
print(5*'===========')
datadeque.append(7)
print('Data Masuk :',7)
print('Data Sekarang :',datadeque)
print(5*'===========')
outdeque = datadeque.popleft()
print('Data Keluar :',outdeque)
print('Data Sekarang :',datadeque)
print(5*'===========')
outdeque = datadeque.pop()
print('Data Keluar :',outdeque)
print('Data Sekarang :',datadeque)
